Test5

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -42,7 +42,7 @@ jobs:
       #     restore-keys: ${{ runner.os }}-pnpm-store-
 
       - name: Install dependencies
-        run: pnpm install
+        run: pnpm install --no-frozen-lockfile
 
       - name: Build project
         run: pnpm build
@@ -53,40 +53,40 @@ jobs:
       - name: Run tests
         run: pnpm test
 
-  e2e:
-    runs-on: ubuntu-20.04
-    steps:
-      - uses: actions/checkout@v3
+  # e2e:
+  #   runs-on: ubuntu-20.04
+  #   steps:
+  #     - uses: actions/checkout@v3
 
-      - name: Install pnpm
-        uses: pnpm/action-setup@v2
-        id: pnpm-install
-        with:
-          version: 7
-          run_install: false
+  #     - name: Install pnpm
+  #       uses: pnpm/action-setup@v2
+  #       id: pnpm-install
+  #       with:
+  #         version: 7
+  #         run_install: false
 
-      - name: Install Dependencies in root folder
-        uses: cypress-io/github-action@v5
-        with:
-          runTests: false
+  #     - name: Install Dependencies in root folder
+  #       uses: cypress-io/github-action@v5
+  #       with:
+  #         runTests: false
 
-      - name: Install dependencies
-        run: pnpm install
+  #     - name: Install dependencies
+  #       run: pnpm install
 
-      - name: Cypress tests
-        uses: cypress-io/github-action@v5
-        with:
-          install: false
-          working-directory: apps/canary-snippet-integration
-          start: npm run dev
-        env:
-          WEB_USERNAME: ${{ secrets.CYPRESS_WEB_USERNAME}}
-          WEB_PASSWORD: ${{secrets.CYPRESS_WEB_PASSWORD}}
+  #     - name: Cypress tests
+  #       uses: cypress-io/github-action@v5
+  #       with:
+  #         install: false
+  #         working-directory: apps/canary-snippet-integration
+  #         start: npm run dev
+  #       env:
+  #         WEB_USERNAME: ${{ secrets.CYPRESS_WEB_USERNAME}}
+  #         WEB_PASSWORD: ${{secrets.CYPRESS_WEB_PASSWORD}}
 
-      - name: Archive cypress video web
-        uses: actions/upload-artifact@v3
-        if: ${{ success() || failure() }}
-        with:
-          name: cypress-video
-          path: apps/canary-snippet-integration/cypress/videos/**/*.mp4
-          retention-days: 30
+  #     - name: Archive cypress video web
+  #       uses: actions/upload-artifact@v3
+  #       if: ${{ success() || failure() }}
+  #       with:
+  #         name: cypress-video
+  #         path: apps/canary-snippet-integration/cypress/videos/**/*.mp4
+  #         retention-days: 30
